[package]
name = "ez_config_macro"
version = "0.1.0"
edition = "2021"
description = "proc_macro crate for ez_config crate"
license = "MIT"

[lib]
proc-macro = true

[dependencies]
syn = "2.0.77"
quote = "1.0.37"
dotenv = "0.15.0"
